apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ssh-keys.clouder.sh
spec:
  scope: Namespaced
  group: clouder.sh
  names:
    kind: SSHKey
    plural: ssh-keys
    singular: ssh-key
    shortNames:
      - sk
      - ssh
      - sshkey
  versions:
    - name: v1
      served: true
      storage: true
      subresources: { status: { } }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Project
          type: string
          priority: 0
          jsonPath: .spec.project
          description: The project the SSH Key is created on.
        - name: Children
          type: string
          priority: 0
          jsonPath: .status.create_ssh-key_fn.children
          description: The children pods created.
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.create_ssh-key_handler.message
          description: As returned from the handler (sometimes).
