# Generated by Terraform. Source this file before running Clouder/Plane commands.
export DATALAYER_AWS_CLUSTER_NAME=${cluster_name}
export AWS_REGION=${aws_region}
export AWS_DEFAULT_REGION=${aws_region}
export AWS_ACCOUNT_ID=${aws_account_id}
export KUBEADM_ADMIN_USER=${admin_user}

export KUBEADM_MASTER_IP=${master_ip}
export KUBEADM_WORKER_IPS="${worker_ips_csv}"

# Copy your PEM/SSH key to ~/.ssh/<name> and use that key name with clouder --key
export KUBEADM_SSH_KEY_NAME=${ssh_key_name}

# ECR endpoints
export DATALAYER_ECR_REGISTRY=${ecr_registry}
